---
title: "Economic_variables_Diego"
author: "Diego Fernández"
date: "2025-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
library(dplyr)
data <- read_dta("ZA7575.dta")
data <- data %>%
  mutate(country_name = case_when(
    q1_1  == 1 ~ "Belgium",
    q1_2  == 1 ~ "Denmark",
    q1_3  == 1 ~ "Germany",
    q1_4  == 1 ~ "Greece",
    q1_5  == 1 ~ "Spain",
    q1_6  == 1 ~ "France",
    q1_7  == 1 ~ "Ireland",
    q1_8  == 1 ~ "Italy",
    q1_9  == 1 ~ "Luxembourg",
    q1_10 == 1 ~ "Netherlands",
    q1_11 == 1 ~ "Portugal",
    q1_12 == 1 ~ "United Kingdom",
    q1_13 == 1 ~ "Austria",
    q1_14 == 1 ~ "Sweden",
    q1_15 == 1 ~ "Finland",
    q1_16 == 1 ~ "Cyprus",
    q1_17 == 1 ~ "Czech Republic",
    q1_18 == 1 ~ "Estonia",
    q1_19 == 1 ~ "Hungary",
    q1_20 == 1 ~ "Latvia",
    q1_21 == 1 ~ "Lithuania",
    q1_22 == 1 ~ "Malta",
    q1_23 == 1 ~ "Poland",
    q1_24 == 1 ~ "Slovakia",
    q1_25 == 1 ~ "Slovenia",
    q1_26 == 1 ~ "Bulgaria",
    q1_27 == 1 ~ "Romania",
    q1_28 == 1 ~ "Croatia",
    q1_29 == 1 ~ "Other countries",
    q1_30 == 1 ~ "DK",
    TRUE ~ NA_character_  # Falls keine der Bedingungen zutrifft
  ))
```

## Economic Variables

Now, we will explore the economic variables

```{r}
# FIRST, we select qc19 question:



economic_variables <- data |> select("qc19", "country_name") 


head(data)

```

